name: AuthPaper
author: Refluxo Development
version: 1.0
api-version: 1.13
main: me.refluxo.auth.paper.AuthPaper
depends:
  - Libary
description: Refluxo Authentification
loadbefore:
  - Libary
load: POSTWORLD
